name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
    paths-ignore: 
      - '.github/**'
      - '**.md'
      - 'LICENSE'
      - 'App/**'

jobs:
  test:
    name: Run build for testing
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
      - name: Install Android SDK
        run: sh ci/install-android-sdk.sh
      - uses: bahmutov/npm-install@v1
      - name: Install npm dependencies
        run: npm ci
      - name: Test Application
        run: npm run test
